### ISSUE TITLE
Recent changes to language file breaks language customisation

### ISSUE THREAD

**Issue by bfriesenvcc** [h5p/h5p-moodle-plugin#360] opened 2020-08-13 22:49 UTC
On the most recent updates of this plugin, the English hvp.php file changed the case of many of the keys. For example,
from...

$string['reuseContent'] = 'Reuse Content';
$string['reuseDescription'] = 'Reuse this content.';
$string['contentCopied'] = 'Content is copied to the clipboard';

to...
$string['reusecontent'] = 'Reuse Content';
$string['reusedescription'] = 'Reuse this content.';
$string['contentcopied'] = 'Content is copied to the clipboard';

This now prevents the EN language pack from being edited. Below, you can see the error message I get AFTER I experimented  by changing ONLY the reusecontent string back to reuseContent in the English hvp.php file, then bumping up the version number and updating it. You see that it then got through the reusecontent string, and crashed at the reusedescription sting. If I were to do the same thing for reusedescription, it would then crash at contentcopied. And so on.

There are discussions about this sort of thing here: https://tracker.moodle.org/browse/MDL-66217 and here: https://tracker.moodle.org/browse/MDL-67302 

So, I don't know if this is something that should (for now) be fixed in the plugin, or just wait for Moodle to fix whatever they need to fix.

==============
Error writing to database
More information about this error

Debug info: Duplicate entry 'en-549-reusedescription' for key 'mdl_toolcust_lancomstr_uix'
INSERT INTO mdl_tool_customlang (lang,componentid,stringid,original,master,timemodified,outdated,local,timecustomized) VALUES(?,?,?,?,?,?,?,?,?)
[array (
0 => 'en',
1 => '549',
2 => 'reusedescription',
3 => 'Reuse this content.',
4 => 'Reuse this content.',
5 => 1597357953,
6 => 0,
7 => NULL,
8 => NULL,
)]
Error code: dmlwriteexception

Stack trace:
line 489 of /lib/dml/moodle_database.php: dml_write_exception thrown
line 1357 of /lib/dml/mysqli_native_moodle_database.php: call to moodle_database->query_end()
line 1403 of /lib/dml/mysqli_native_moodle_database.php: call to mysqli_native_moodle_database->insert_record_raw()
line 191 of /admin/tool/customlang/locallib.php: call to mysqli_native_moodle_database->insert_record()
line 60 of /admin/tool/customlang/index.php: call to tool_customlang_utils::checkout()

**Comment by thomasmars** [comment] 2020-08-17 07:57
This is a duplicate of https://github.com/h5p/h5p-moodle-plugin/issues/313. Please use that thread.

**Closed by thomasmars** 2020-08-17 07:57 UTC
