### ISSUE TITLE
Content dissappeared after upgrading the plugin

### ISSUE THREAD

**Issue by Jarvil** [h5p/h5p-moodle-plugin#146] opened 2017-04-07 11:17 UTC
Hello,

We upgraded Moodle H5P-plugin to version 1.0 and also all the content types, after this when we opened already before built H5P-activity (Question set with multichoice questions) and we got an error message;

"The version of the H5P library H5P.MultiChoice used in this content is not valid. Content contains H5P.MultiChoice 1.8, but it should be H5P.MultiChoice 1.9."

And after second time clicking the H5P-activity all the content has dissappeared. Any advice how to get the content back?

![error](https://cloud.githubusercontent.com/assets/15193418/24798032/9f4c4c7c-1b9c-11e7-93a0-e9ad13f60b7e.png)

**Comment by Jarvil** [comment] 2017-04-07 11:18
Someone have had the same problem here;

https://moodle.org/mod/forum/discuss.php?d=347744

**Comment by Jarvil** [comment] 2017-04-07 11:22
Hello,

/mod/hvp/library_list.php

shows that we have zero (0) Multiple Choice (1.8.0) and Multiple Choice (1.9.2) and zero Question Set (1.9.0) but 10 Question Set (1.12.0)

**Comment by Jarvil** [comment] 2017-04-07 11:49
When I download the h5p package it still is 600KB in size so its not empty it just doesn't show up.

**Comment by icc** [comment] 2017-04-07 11:52
I can confirm that there's a bug with the upgrade. I am currently, looking into where it could be. Please don't resave the activities as this may destroy the content.

**Comment by icc** [comment] 2017-04-07 13:18
The good thing is that I found the bug and created a fix for it: bae82c9
I assume it will be released as quickly as possible.

The bad thing is how do we fix the content? The problem is that the upgrade was run but the content wasn't actually upgraded. If you don't have a backup of the activities the easiest fix is to 'reset' the version that the content uses and then run the upgrade process again(after applying the fix, of course). In your case, for Quiz(Question Set) you can reset the version using the following query:
```
UPDATE mdl_hvp 
   SET main_library_id = (SELECT id
                            FROM mdl_hvp_libraries 
                           WHERE machine_name = 'H5P.QuestionSet'
                        ORDER BY major_version DESC, 
                                 minor_version DESC 
                                 LIMIT 1, 1) 
 WHERE main_library_id = (SELECT id
                            FROM mdl_hvp_libraries 
                           WHERE machine_name = 'H5P.QuestionSet'
                        ORDER BY major_version DESC, 
                                 minor_version DESC 
                                 LIMIT 1) 
```
NOTE that you may be using a different table prefix than `mdl_`. 
I've only tested it in MySQL but it should work for most databases.

Let me know if you have any questions.

**Comment by Jarvil** [comment] 2017-04-11 10:44
Hello,

We have upgraded the plugin (stable branch), run the database query to reset the library version, and then upgraded the Question Set library again but we still get error in Interactive video -content.

![virrrrhe](https://cloud.githubusercontent.com/assets/15193418/24905550/068924e6-1ebd-11e7-81f9-9ffa8ca54207.png)

**Comment by icc** [comment] 2017-04-12 07:33
That is strange, did the UPDATE query say how many rows it affected? e.g.
```
Query OK, 53 row affected (0,02 sec)
```

I just tried resetting it(query) and then running the upgrade process again with the fix on my local moodle site and it worked. Are you positive you added the fix from the stable branch before doing the upgrade again?

**Comment by Jarvil** [comment] 2017-04-12 07:43
Hello,

I ment that Question set works now but interactive video doesn't.

**Comment by icc** [comment] 2017-04-12 07:49
Ah, I'm sorry, my eyes must be getting tired. You should be able to do the same process for any content type, you must just be sure to replace the two instances of the 'machine_name' in the query, e.g. 
```
UPDATE mdl_hvp 
   SET main_library_id = (SELECT id
                            FROM mdl_hvp_libraries 
                           WHERE machine_name = 'H5P.InteractiveVideo'
                        ORDER BY major_version DESC, 
                                 minor_version DESC 
                                 LIMIT 1, 1) 
 WHERE main_library_id = (SELECT id
                            FROM mdl_hvp_libraries 
                           WHERE machine_name = 'H5P.InteractiveVideo'
                        ORDER BY major_version DESC, 
                                 minor_version DESC 
                                 LIMIT 1) 
```
To get a complete mapping between machine_name and title used in the UI you can run the following:
```
SELECT DISTINCT machine_name, title FROM mdl_hvp_libraries WHERE runnable = 1;
```

**Comment by Jarvil** [comment] 2017-04-12 07:52
Hello,

Ok thanks for the quick replys 😃

**Comment by icc** [comment] 2017-04-12 07:53
No worries, just let me know if you run into any issues!

**Closed** 2017-08-15 09:55 UTC
