### ISSUE TITLE
UI compability issues with Boost theme

### ISSUE THREAD

**Issue by Jarvil** [h5p/h5p-moodle-plugin#183] opened 2017-11-23 12:39 UTC
Hello,

It seems H5P 1.5 doesn't work good with Moodles Boost-theme, you should check that everything looks good with it. Boost is the new Moodle coretheme since version 3.2. Here are couple of screenshots of the problems. The course presentation is quite tiny.

![lista](https://user-images.githubusercontent.com/15193418/33173228-1150f7fe-d05c-11e7-8388-2ee86a86b93f.PNG)

![lista2](https://user-images.githubusercontent.com/15193418/33173234-151ac950-d05c-11e7-93b3-92b0df8eef9e.PNG)

**Comment by Jarvil** [comment] 2017-11-23 12:41
You cannot really use any H5P libraries at all since the view is so narrow @thomasmars 

![lista3](https://user-images.githubusercontent.com/15193418/33173291-49b43976-d05c-11e7-92be-06f60cde4c2a.PNG)

**Comment by thomasmars** [comment] 2017-11-24 12:56
We have tested H5P rigorously with the Boost theme, so this should not be happening, do you have any special mode for your site, any modifications to your theme or any plugins that might be causing this ?
I have installed a fresh Moodle 3.2 site with H5P 1.5 and the Boost theme and am not able to reproduce this. I have also done extended testing with Moodle 3.3 and 3.4 with the same setup.


![localhost_course_modedit php_add hvp type course 2 section 0 return 0 sr 0 1](https://user-images.githubusercontent.com/1640201/33211518-3b9af2a8-d11f-11e7-9076-c66bf4881437.png)

![localhost_course_modedit php_add hvp type course 2 section 0 return 0 sr 0 2](https://user-images.githubusercontent.com/1640201/33211523-41761b4e-d11f-11e7-9b9a-235e47a029a4.png)

If we're to find the root cause of this we need more information on what is happening on your site, can you look into what css is causing this ?

**Comment by albertolarah** [comment] 2017-11-24 13:04
I have the same problem. 
The problem is in the form-control-static class
![image](https://user-images.githubusercontent.com/1539802/33211776-63e6eca2-d120-11e7-8da9-9907ef2aac60.png)

**Comment by Jarvil** [comment] 2017-11-24 13:05
Hello,

I will check that, it might be possible. Did you try if you can add interactive video to your couse presentation?

**Comment by albertolarah** [comment] 2017-11-24 13:13
@Jarvil  The problem is the Moodle versión not the h5p plugin.

**Comment by davidscotson** [comment] 2018-10-08 08:57
I needed to put a fix in for this on Moodle 3.4 (the problem showed up for me in Boost and in my custom theme). I can't tell from the above thread whether this is considered fixed in core or not?

My workaround was:
#page-mod-hvp-mod .form-control-static {
    display: block !important;
}

Running version 2018053100 of hvp and '3.4.3+ (Build: 20180607)' of Moodle (and Boost)

**Comment by thomasmars** [comment] 2018-10-10 07:44
Hi,
This is essentially a regression issue with the Boost theme in Moodle. They have an issue for it, but there doesn't seem to be anything happening: https://tracker.moodle.org/browse/MDL-58021
For now we have a hack for a workaround for the 'boost' theme, and any theme that inherits from the boost theme: https://github.com/h5p/h5p-moodle-plugin/blob/stable/mod_form.php#L60-L68.
There's not much more we can do about this, we can't make exceptions for every theme that has this problem when we see it, so we're waiting for the fix by Moodle. In the meanwhile you'll unfortunately have to create your own css workaround, like you've done, if you have a theme that is not covered by our workaround.

**Closed by thomasmars** 2018-10-10 07:44 UTC

**Comment by Jarvil** [comment] 2018-11-28 07:42
Hello,

This is still an issue with Moodle 3.5.3, H5P editor with Boost is unusable/tiny.

**Comment by thomasmars** [comment] 2018-11-28 10:17
![boostthemeh5peditor](https://user-images.githubusercontent.com/1640201/49145057-34219b00-f2ff-11e8-845a-8a18fd5ee014.png)
I see nothing wrong with H5P Editor in Boost theme when using Moodle 3.5.3, please explain.

**Comment by Jarvil** [comment] 2018-11-28 10:33
Hello,

I tested with Moodle 3.5.3 (Build: 20181112) & theme_boost 2018051400, do you have the same versions? Here are couple of pictures.

![boost1](https://user-images.githubusercontent.com/15193418/49145996-d5155380-f309-11e8-82ad-41492f1fc7a6.PNG)
![boost2](https://user-images.githubusercontent.com/15193418/49146006-d9417100-f309-11e8-9d35-b8af24a8cb6f.PNG)

**Comment by Jarvil** [comment] 2018-11-28 10:36
Hello,

It seems you are missing the wide margin on the right and the "box" around the middle section of the theme, please try to add to a course.

**Comment by thomasmars** [comment] 2018-11-28 10:44
Yes, Moodle 3.5.3 (Build: 20181112), and theme_boost 2018051400.
What H5P version are you using ?
Please check the css for the container of the editor, should be '.h5p-editor', and if you have any special css or plugins that may be conflicting with the H5P css.

**Comment by thomasmars** [comment] 2018-11-28 10:50
![boostthemeh5peditor2](https://user-images.githubusercontent.com/1640201/49146905-7a78f900-f303-11e8-878f-d3a966b61a0b.png)
I'm in a course, but I don't have any right margin, do you have any special settings for the theme?

**Comment by Jarvil** [comment] 2018-11-28 10:55
Hello,

I got the editor to work normally with Boost-theme. The problem occurs in a case when you have selected some other theme f.ex Clean for the whole site and force boost just on a course level from the course settings (force theme).

Allowing course themes to be used in Moodle can be done from:

https://moodleaddress.com/admin/settings.php?section=themesettings&lang=en

Site administration
Appearance
Themes
Theme settings
-> Allow course themes | allowcoursethemes

And after that from the course settings:

Appearance -> Force theme -> Boost -> Save changes and display

**Comment by thomasmars** [comment] 2018-11-28 11:43
Thanks, I've created an issue to extend the CSS workaround for the described use-case as well in https://h5ptechnology.atlassian.net/browse/HFP-2443.
Hopefully Moodle will fix https://tracker.moodle.org/browse/MDL-58021 soon, so we don't have to rely on workarounds though.

**Comment by Jarvil** [comment] 2018-11-28 11:45
Hello,

Thank you.
