### ISSUE TITLE
New embed feature.  Course copy process does not update embed code.  Copy points to h5p activity in parent course.

### ISSUE THREAD

**Issue by BirdyOz** [h5p/h5p-moodle-plugin#184] opened 2017-11-30 02:48 UTC
Hi guys.  I am thrilled to see embed code feature has now made it to the Moodle plugin.  I have run this up on Moodle3.3 and it works well.

..............UNTIL ................

When you copy a course through the standard backup and restore process, this new copy points to the H5P activity in the original (parent) course., and NOT to the H5P activity in the copied (child) course.

This causes issues of permissions.  For instance, if you are a student in the child course, but NOT in the parent, you cannot see the H5P activity.  If you are a student in BOTH and complete the activity in the child course, the grade is recorded in the parent course.

**Comment by thomasmars** [comment] 2017-12-07 14:06
Hi,
Thank you for the feedback.
I can see how this is a problem, we need to determine when to rewrite the reference to the embedded content and when not to.

As I can see it the scenarios should be as follows:
- When only copying content with a reference to embedded H5P content the copied content should still reference the original content
- When only copying H5P content embedded content that points to the original content should still point to the original content.
- When copying BOTH content that has a reference to embedded H5P content AND the H5P content itself that was pointed to the reference in the copied content should update to the new H5P content

Can you verify that this makes sense?

Are there any more scenarios that we should be aware of where it makes sense to rewrite the embed code ?

I have created an issue for resolving this in the official issue tracker, https://h5ptechnology.atlassian.net/browse/HFP-1786, where you can keep an eye on the progress. Hopefully we'll be able to resolve this quickly.

**Comment by BirdyOz** [comment] 2017-12-07 21:43
Hi Thomas.  Thanks for this reply. 
Sorry if this is over-long, but I am trying to capture the scope of the issue for you.

I am not sure that your scenarios properly capture the issue as it relates to Moodle, so I am providing additional detail that might help in resolution.  

This issue is a specific result of the Moodle course copy process.

In Moodle, each activity that is added to a course has a unique Course Module ID (CMID).  Therefore, as you add H5P activities to a Moodle course, they are each issued a CMID.

In the moodle database, Moodle maintains a table 'mdl_course_modules' that identifies which activities (CMID) belong to which Course ID (CID)

Course 1 (CID: 1234) 
- H5P activity (CMID: 10007)
- Moodle page with embedded H5P activity (CMID: 10008)

In this way, each activity (CMID) is unique to a specific course (CID)

[See here for a diagram: ](https://i0.wp.com/www.azhowto.com/wp-content/uploads/2013/04/course_relationships.jpeg?ssl=1)

Your H5P embed code then refers to that specific CMID, (eg CMID: 10007)

So far so good.  If you create a Moodle page, the correct H5P activity is displayed in the correct place.

The problem comes when the course is copied.  Copied courses get a new CID and each activity in the course is copied and given a new CMID:

Course 2 (CID: 1235)  [copy of CID: 1234]
- H5P activity (CMID: 10023)
- Moodle page with embedded H5P activity (CMID: 10024)

The H5P embed code is NOT UPDATED in the copy process and continues to point to original H5P activity (CMID: 10007) in the PARENT coarse (CID: 1234).

Even though there is a new copy of the H5P activity (CMID: 10023) in the CHILD course this is effectively an orphan and is not referenced by your embed code.  As such the internal course integrity is lost.  Updates to this new H5P activity WILL NOT be reflected in the embedded content.

As permissions are issued at the Course level, it is possible that a student only has permissions to the CHILD course, and so is not permitted to see the H5P activity, because it is "owned" by the PARENT course.  At this point, they get a file permissions error.

Ideally, the course copy process would trigger a rewrite of the embed code to point to the new copy of the H5P activity CMID (CMID: 10023).  The CORE copy process does do some integrity checking and rewrites internal links for some elements (a, img etc), bit appears it does not rewrite iframe embeds.

Perhaps someone from Moodle HQ could advise on this

I hope this helps, and is not overly confusing.

**Comment by thomasmars** [comment] 2017-12-08 10:26
Thank you, that makes sense. The challenge will be to determine whether both the embed code and the H5P is being copied to a new course then resolving the new CMID of the copied H5P activity and referencing this in the Moodle page. I'm not sure if the H5P plugin will have access to the page activity to modify the embed code correctly, but figuring this out will be part of the implementation job.

I guess the main way to copy a course is to first use backup, then restore the course to a new course. Is this the preferred way you do it ?

Thank you again for the detailed description of the problem, we'll make sure to look further into this when we're able to prioritize this issue.

**Comment by BirdyOz** [comment] 2017-12-10 23:26
Hi Thomas.  Backup and restore is a very common method for duplicating a Moodle course. 

There is also "Import" which allows you to copy (import) either a whole course, or discrete Moodle activities between courses.

As you say, the trick is to first establish whether the H5P embed is pointing to the correct H%P activity, and then update the embed code if necessary.

I suspect this a non-trivial exercise as I doubt the plugin is currently monitoring such processes.  I could see three possible solutions, but, not being a plugin developer, I don't know whether/how hard they would be to implement.

1. Easiest (I think).  have the H5P 'embed' code actually just produce a standard href, then use javascript to dynamically transform this to an iframe embed at runtime.  

`<a class = "hvp-embed" href = "https//:path.to.moodle/mod/hvp/view.php?id=CMID" .....`

Is dynamically transformed by jQuery (for example):
`$.each('hvp-embed', function() {
     /* Do stuff */
});`

to become:
`<iframe src="https//:path.to.moodle/mod/hvp/view.php?id=CMID ....."`

The great advantage is that Moodle's own core processes that 'rectify' internal links during import and course restore will rectify the href.



2.  Liaise with Moodle HQ to see whether the core processes that 'rectify' internal links during import and course restore can be extended to iframe embeds. - I suspect this a long-term solution
3.  Develop a CRON that monitors H5P created iframe embeds and confirms that the embed points to a h5P activity within the same course.  If not, it rectifies the embed code

**Comment by alanpt** [comment] 2017-12-11 01:46
We do something similar. All links to h5p activities get automatically embedded.  Unfortunatly it doesn't automatically resize to the correct height. So our hack is to add a height within square brackets in the title. We also use css to hide all non-h5p content in h5p activity pages. Here is the javascript code, keen for any hints on doing this better: 

`/* Turn h5p links into embeds */
$("body").ready(function() {
	$(".activityinstance a").each(function() {
		// get all the links inside the .activeinstance elements
		var $this = $(this); // ...
		var $parent = $this.parent(); // get the parent of the link
		var href = $this.attr("href"); // get the href of the link
		if (href.indexOf("/hvp/") == -1) return; // if the href doesn't contain '/hvp/' then skip the rest of this function (where the replacement happens)
		var span_val = $(this).text();
		//		var spanheight = span_val;
		var iframeheight = span_val.substring(
			span_val.indexOf("[") + 1,
			span_val.indexOf("]")
		);
		//		iframeheight = spanheight.slice(1, 4);
		console.log(iframeheight);

		$this.remove(); // remove the link as I don't see any reason for it to be inside the iframe
		$parent.append(
			"<div style='width:700px; height:" +
				iframeheight +
				"px'><iframe frameborder='0' allowfullscreen='allowfullscreen'  src='" +
				href +
				"&isembedded=1&h5p=1' style='width:100%; height:100%;'></iframe></div>"
		); // add an iframe with the src set to the href to the parent of the link
	});
});`

**Comment by BirdyOz** [comment] 2017-12-11 03:32
Yes, that's very much like what I can imagine will work for dynamic Moodle embeds.  The jQuery targetting and pattern matching would differ, but the structure looks re-usable.

Later this week, I will see if I can hack your code to produce an implementation that might work in Moodle.

**Comment by alanpt** [comment] 2017-12-11 21:05
Would this be best made as a Moodle Filter?

That was going to be my next project. Currently being able to add "Interactive Content" where ever we want in topics and have them auto-embed (using this script) does what we need.  In our scenario we don't need to embed them within labels, or other activities/resources.
If we had a an automatic filter and the h5p library copying bug was fixed, we would be happy as Larry.

I guess having it happen in the backend would be better.

**Comment by BirdyOz** [comment] 2017-12-11 22:18
By filter, do you mean a media filter, such as the one that automatically detects links to YouTube videos and converts them to an iframe embed?  (Site administration / ▶︎ Appearance / ▶︎ Media embedding).  If so, then yes, this might work.

When you say _"In our scenario, we don't need to embed them in labels, or other activities/resources.", I would disagree and can actually see great value in this being possible.  

The whole reason our teachers are interested in being able to embed H5P activities is so that they can scaffold and contextualise your great interactives within their own learning content.

This could be in the form of any Moodle activity, such as a label, book, lesson, page or discussion forum ...... whatever best serves the learning design.

**Comment by alanpt** [comment] 2017-12-11 22:58
Cool I'll give the filter building a try.
  
Our specific Moodle design has topics in tabs and sub tabs - and as much as possible we embed all resources and activities in the tabs with context and scaffolding around them (using labels). I can definitely understand the importance of embedding when using Moodle the standard way though for the reasons you mention.

**Comment by BirdyOz** [comment] 2017-12-20 04:09
Hi Alen.

Thanks for all your work and please reach out to me if you would like me to beta-test any solution(s) you may have to this issue.

The more I experiment, the more I think that the filter approach is the most solid, as it can then hook into core processes within Moodle that update internal links when copied (through backup and restore) or imported.

Merry Christmas, Greg

**Comment by monnardj** [comment] 2017-12-20 13:57
To solve the problem of embed links not being restored correctly, you must use the mechanisms provided by Moodle (which H5P already uses for regular links to H5p activities) :

1. In /mod/hvp/backup/moodle2/backup_hvp_activity_task.class.php, add the following lines in function encode_content_links :
`        $search = "/(".$base."\/mod\/hvp\/embed.php\?id\=)([0-9]+)/";`
`        $content = preg_replace($search, '$@HVPEMBEDBYID*$2@$', $content);`
This tells Moodle that links to H5P activities embedded anywhere in Moodle content should be encoded with "HVPEMBEDBYID"

2. In /mod/hvp/backup/moodle2/restore_hvp_activity_task.class.php, add the following line in function define_decode_rules :
`        $rules[] = new restore_decode_rule('HVPEMBEDBYID', '/mod/hvp/embed.php?id=$1', 'course_module');`
This tells Moodle that instances of HVPEMBEDBYID should be decoded and replaced with an embed link to the copied H5P activity.

And presto, it works : embedded H5P activities in a copied course now point to the correct H5P activity in the same course :-)

Cheers,
Jacques

**Comment by thomasmars** [comment] 2017-12-20 14:23
@monnardj Thank you.
This solves the problem when copying a resource that points to and H5P activity when they are both in the same course I assume.
For 1 you say that this will tell Moodle that links to H5P activities embedded **anywhere** in Moodle content will be encoded with "HVPEMBEDBYID" and be replaced. Does this mean that if I have a Moodle "page" activity in Course 1 pointing to a H5P activity in course 2, then copy course 2 to a course 3, will the Moodle "page" now be pointing to the H5P activity in course 2 still, or be updated to point to the H5P activity in course 3 ?

I assume that users would expect it to still point to the H5P in course 2, however if they have a page and an H5P activity, both in course 2, then they would expect the behaviour to be that the copied page in course 3 would now point to the H5P activity in course 3.

Would this be handled properly with the above suggestion? And does the described behaviour make sense ?

**Comment by monnardj** [comment] 2017-12-20 14:58
Well, first, a disclaimer : I'm no specialist in the whole Moodle backup/copy/restore process. What I say below is only my understanding, and more knowledgeable people should correct me if I'm wrong !

The two steps I mentioned in my solution above are only applied when a whole course is backed up (step 1) and restored (step 2), and they only apply for an H5P activity which has been copied. Other courses with links to the copied activities are not affected.

Note also that the current H5P code already includes encoding/decoding rules for regular links to H5P activities, so my comments below apply to both regular links and embed links to H5P activities.

> Does this mean that if I have a Moodle "page" activity in Course 1 pointing to a H5P activity in course 2, then copy course 2 to a course 3, will the Moodle "page" now be pointing to the H5P activity in course 2 still, or be updated to point to the H5P activity in course 3 ?

The link decoding process is only executed in the copied course (course 3 in this case), so nothing changes in course 1, and the embed in course 1 will still point to the H5P activity in course 2.

> I assume that users would expect it to still point to the original H5P activity in course 2

That will be the case.

> however if they have a page and an H5P activity, both in course 2, then they would expect the behaviour to be that the copied page in course 3 would now point to the H5P activity in course 3.

And this will also be the case. Since the whole course has been copied (including the H5P activity), Moodle adapts all internal links to copied activities.

This is the way Moodle works for all types of activities, and this solution seems to satisfy most users.

**Comment by BirdyOz** [comment] 2017-12-21 03:55
Hi all,

I think that the solution suggested by @monnardj sounds very promising.  Have you rolled up a version of the plugin that includes these code changes?  I'd be delighted to test this for you.

RE: @thomasmars 
>  I have a Moodle "page" activity in Course 1 pointing to a H5P activity in course 2

I think that cross-linking between Moodle courses is massively problematic.  In Moodle, permissions are given at the course level.  

- If a student is enrolled in Course 1, but **NOT** in course 2, they will not have permissions to view the H5P activity and they will receive an error.
- If a student is enrolled in **BOTH** Course 1 and Course 2, they will be able to view the H5P activity in Course 1 **BUT** the result will be recorded in Course 2

**Comment by falcon-git** [comment] 2017-12-21 14:49
Great contributions! Thomas is in Christmas mode right now, and I'm not sure if he'll be answering until January. We're also very interested in a filter approach. If anyone has more to share there or even better are able to put together patches or PRs I'm sure Thomas will look into them after Christmas

**Comment by monnardj** [comment] 2017-12-22 07:24
While I can understand the interest of a filter approach, I would suggest treating it as a separate issue. As it stands, the current version of the H5P plugin doesn't behave consistently when a course is copied.

Let me give you an example : course A contains an H5P activity. In the same course, there is a "page" resource, which contains both a link and an embed of the H5P activity. Course A is then copied to course B. In the copied page in course B, the link will point to the copied H5P activity in course B (this is the expected behavior in Moodle), but the embed will still point to the original H5P activity in course A (not correct).

The (simple) fix I proposed above would solve just that issue and make H5P activities behave like all other Moodle activities in copied courses.

**Comment by monnardj** [comment] 2018-01-24 15:59
I've now submitted a [pull request](https://github.com/h5p/h5p-moodle-plugin/pull/194) with the fix described above.

**Comment by thomasmars** [comment] 2018-01-26 11:42
Excellent work, looks good! The pull request will be followed up in the issue that you linked to.

**Comment by louisebennett** [comment] 2018-02-13 10:19
Any update on getting this fix released? We really need this feature.

**Comment by kang17** [comment] 2018-04-04 19:54
yes,, this is really needed for us too! Hoping this fix can come soon!

**Comment by cafranks** [comment] 2019-01-09 16:02
The Backup/Restore feature is the only thing blocking our school from adopting h5p in our Moodle instance - and has been for 2 years - would be great to see this resolved!

**Comment by mgancarzdsi** [comment] 2019-01-09 16:49
Noting that this is also a blocker for us adopting H5P widely.

**Comment by thomasmars** [comment] 2019-02-20 15:51
This is now available in version 1.15. Thanks to everyone who contributed.

**Closed by thomasmars** 2019-02-20 15:51 UTC
