### ISSUE TITLE
Embed H5P Content into Page Resources

### ISSUE THREAD

**Issue by icc** [h5p/h5p-moodle-plugin#30] opened 2016-01-05 12:16 UTC
Should we make it possible to insert H5P Content into the _Page_ resources?

**Comment by xyulex** [comment] 2016-02-16 08:28
You can do that by simply going to HTML view of the editor in Moodle and copy-paste the  <iframe> code.

**Comment by icc** [comment] 2016-02-16 09:53
I'm sorry, I wasn't very clear. What I meant was a solution like in WordPress, where you use shortcodes to insert the content into other components. This can be useful if you do not have the permission to write HTML(iframe or script tags) into Pages or other resources. However, this might not be an issue on Moodle? 
I'm not(yet!) very experienced in the different usage patterns in Moodle, but I hope to learn :-)

**Comment by xyulex** [comment] 2016-02-16 10:02
Well, if you are a content creator in Moodle (i.e. you have an 'Editing teacher' role), you can actually insert it:

via 'Multimedia' button, which is a user-friiendly method
via <> Icon, which is a more developer method, in which you should copy your embed URL

There isn't anyhting similar to WordPress shortcodes in Moodle.

**Comment by icc** [comment] 2016-02-16 10:24
Ok, thank you for the feedback.

**Comment by brum1975** [comment] 2016-03-11 11:25
I think the way to do this is by creating an "Atto" plugin.

**Comment by nadavkav** [comment] 2016-04-08 18:34
I have tried to develop a Moodle filter for h5p mod (hvp) and got stuck with trying to load all the H5P libraries before the $PAGE initiates, and could not find the proper way to do so.
Here is a link to a wip of this: https://gist.github.com/nadavkav/155cc21df9cd19e9ee1f6760462b62cb

And so...
Add to the hvp/view.php the following hack:
$isembeded = optional_param('isembedded', false, PARAM_BOOL);
...
if ($isembeded) {
    $PAGE->set_pagelayout('embedded');
}

And used IFRAME to embed it into a Moodle Page resource (actually, anywhere)
<iframe class="h5p-embed" src="http://moodle-site.org/mod/hvp/view.php?id=XXX&amp;isembedded=1" width="100%" height="500px"></iframe>

**Comment by nadavkav** [comment] 2016-04-08 18:38
When we fix the filter, we would definitely have an ATTO plugin (toolbar button) for our Academic stuff that is displaying a list of hvp resources in the current course. clicking on one of them will generate the proper filter syntax and embed it into the content (similar to wordpress shortcodes)

Maybe, we will use the Generico filter

**Comment by icc** [comment] 2016-04-13 07:37
This looks like some steps in the right direction, good work nadavkav! 
I'm not able to see why it isn't working, but I haven't done any testing yet. 
I guess we should have made a class or some functions so that we wouldn't have to duplicate so much of the code from view.php. I will fork it and do some testing when I get some spare time on my hands. 
Again, this looks like a nice contribution and I think it will enrich the plugin!

**Comment by nadavkav** [comment] 2016-08-06 09:05
Update: We developed an ATTO plugin that list all the H5P activities in the course. choosing one, it embed it as an IFRAME in the editor and adds the above suggested extra param that display it in EMBED mode.

Please see if the above suggestion (display H5P activity in Embed mode) make sense, and if so... I will be happy to share the ATTO plugin code. If you are going with the filter option... we will easily update the ATTO plugin to support it and then share it too :smile:

**Comment by nadavkav** [comment] 2016-08-06 16:51
We are using some WIP beta H5P backup code which works. but I guess it will be available publicly on the next release. so we don't have any issues.

Normally, Moodle can restore links with specific IDs to course activities even when the course backup is restored on a different system. (It scan the links in the content and create a map of the old and the new activity IDs) I guess our current H5P links to the view.php?id=XXX&embed=1 will not break. but I did not had the opportunity to test it yet. (I will). 
If we use an H5P filter plugin, which will probably use some kind of "shortcode" I am not sure if it will still work when the course content is restored on a different Moodle system.

**Comment by lewiscarr** [comment] 2016-09-05 09:23
Hi all, I have a need to build the H5P content in a course but need to be able to embed it in other courses as a label, is the embed code disabled somewhere else in the code or just on the hvp/view.php page? There is certainly the need to enable embed, even if it's a read-only, non-gradebook writing view.

**Comment by berrandonea** [comment] 2016-09-15 14:03
Hello,

This atto plugin nadavkav talked about could be exactly what we need. Where can we find it ?

**Comment by nadavkav** [comment] 2016-09-18 12:48
Here is a link: https://github.com/nadavkav/moodle-atto_hvp

It's working, but, it's a hack. and I think we should have better support
and agreement with core h5p developer on the proper way to implement these
kind of usages.

**Comment by berrandonea** [comment] 2016-09-19 10:27
Thank you very much. It works !

**Comment by berrandonea** [comment] 2016-09-19 12:40
Well, it doesn't work with all themes. But with another little hack in my theme (archaius), I could fix this.

**Comment by nadavkav** [comment] 2016-09-19 13:18
Yep, you just need to make sure you have a very minimal and clean layout in each theme that shows only the content and nothing else.

**Comment by nickvarney** [comment] 2016-10-17 16:04
I just wanted to echo previous comments, in particular Lewis Carr's and say that in my opinion having the _option_ to embed h5p content (in Pages, Labels etc) will be a big plus for the adoption of h5p in Moodle. Embeds on a main course page would do a great deal towards increasing our learners; engagement with the rest of the course for example.
 
Of course users can create content in h5p.org and embed that way but  an in-Moodle solution would be far slicker and obviously better in terms of content management, privacy, confidentiality etc

**Comment by mgancarzdsi** [comment] 2016-10-17 16:40
Hear heard, thirded.

**Comment by nadavkav** [comment] 2016-10-17 19:05
Reading through this issue again, and as I didn't seem to mention it before...
We add H5P activities to a special Moodle course topic (section/module/unit...) and then hide it and also set each H5P activity in it to "visible". It's a Moodle hack, to make all the H5P activities visually hidden from students viewing the frontpage of the course, BUT available to be embedded everywhere in the course, using the above (linked) Atto H5P embed plugin.

**Comment by opinco** [comment] 2016-10-18 23:43
Hi, I'm glad to contribute a Spanish lang package for Moodle. But, as a non-programmer, I found that every extended character like é, ñ, Á etc. appears as � in my Moodle installation. How do I convert this characters? Find attached the lang file.
[hvp-lang-es.txt](https://github.com/h5p/h5p-moodle-plugin/files/537604/hvp-lang-es.txt)

**Comment by pvo-it** [comment] 2016-10-27 19:54
We would like to embed into pages and/or books. The problem is we don't have access to add the plugin to atto.  We use a Moodle partner who would probably frown on using a hack, or charge us to install it.

I was thinking about creating an open course. (all users are enrolled) as a sort of repository, then embedding the code into a page or assignment in the active course. 

We would have to enroll all students, but wouldn't want them to access the course. This course would become a repository of H5P content that could be embedded into other courses. 

Has anyone thought of, or attempted something like this. 

I sure wish there was an easier solution than these work arounds.

What I would really like to see is HTML source code access in H5P text editors.

**Comment by alanpt** [comment] 2016-10-27 20:06
Yea, we are in the same situation as pvo-it above.  The problem with that solution is - the grades aren't attached to the course then. So it would be difficult for the course tutor to mark.

At the moment we use a separate hosted drupal site to make embeddable h5ps alongside the Moodle one.  

- For formative activities (non-marked), we use the drupal embeds; 
- For summative activities (marked), we use the moodle h5p activities (showing on separate pages).

It's a solution that works for now, but could get cumbersome in the future.

**Comment by mgancarzdsi** [comment] 2016-10-27 20:14
Hi @pvo-it , watch/vote for https://tracker.moodle.org/browse/MDL-4782 to get implemented to do what you want, ie: a way to embed from another activity that is hidden, but accessible by direct link.

**Comment by pvo-it** [comment] 2016-10-27 21:06
Thank you mgancarzdsi 
I voted. This issue has been a sore spot for a long time. Sounds like it is being addressed. Hopefully a solution will be part of Moodle core soon.

**Comment by nickvarney** [comment] 2016-11-07 16:11
I've voted too.
The h5p atto editor (above) is a good piece of work but with our site's template it displays too much extraneous information for us to use it (all the site's left hand side blocks appear with the h5p content).

**Comment by tmkettunen** [comment] 2016-11-10 11:16
Is it impossible just to add the embed function for Moodle? Maybe with a notifification that using the embed code will not record points/grades and that the course has to be accessible without a login for the embed to actually work outside the course.

**Comment by pstencel** [comment] 2016-11-10 11:42
Maybe I'm missing something obvious here (apologies, in that case), but why can't the grades be recorded for embedded H5P activities? Suppose we have a collection of H5P activities in a hidden topic of a moodle course and then we embed those activities in a page (or lesson, or quiz, or any other moodle module). The grades might be recorded in the original H5P activity (the one in the hidden topic), right?

**Comment by mhughes2k** [comment] 2016-11-10 13:53
The option to generate it as a "hidden" activity means that the hidden activity holds the resultant score, not the resource that is *displaying*.

So if you happened to embed the "hidden" h5p activity on to 2 pages, then the user could think they are doing 2 different activities, when in reality they're doing the same one twice...(however if you were to guarantee that you'd never do this, then it would work, caveats about users deleting the H5P content, or switching to course formats that expose it or do something else aside...)

I think that @brum1975 is correct, it *should* be an Atto plugin that would display an H5P editor for creating an H5P activity *within* the text editor (this would allow H5P content to be placed *anywhere* that an HTML editor appears).

However I've had a play with doing this, and the 1st problem that I ran into was that Atto Plugins *have* to be implemented as YUI modules, and the H5P editor is jQuery based, and is expecting jQuery objects to represent some of the UI controls that it requires to read information from (e.g. create / upload).

The 2nd problem is then how do you pass the grade information from each embedded H5P activity to the displaying Moodle component. Bearing in mind that Moodle components such as Page don't expect to present a grade to students! Some components like Lesson in theory do provide a grade at the end of them, but you'd need some mechanism to tell Moodle how to put all of the H5P activity content together into the final grade for the *Moodle* activity.

**Comment by wullie** [comment] 2017-01-10 16:59
@nadavkav I tried your workaround and it worked well for the accordion type, except it obviously has a 'window' size which expands out with a scrollbar. Is there anything quick and easy way to change the code to have it expand the page and shift everything else down rather than fit to a window?

**Comment by nadavkav** [comment] 2017-01-10 19:50
As far as I know, you will need some JS code to resize it. If you are using Moodle, you can use some YUI code to do that or anywhere else you can use jQuery. Does this help?

**Comment by wullie** [comment] 2017-01-11 10:04
When copy/pasting the embed code from h5p, there is a reseize script added to the bottom of the iframe (script src="https://h5p.org/sites/all/modules/h5p/library/js/h5p-resizer.js" charset="UTF-8"></script). If I replace your script with this would that resolve my issue? What about if I added it to the end of your code?

**Comment by wullie** [comment] 2017-01-11 10:10
Figured I should stop being lazy and tried both, but neither worked. Replacing your code shrunk the box down to a small height with the scroll bar and adding the code at the end of your script made no difference.

**Comment by nadavkav** [comment] 2017-01-11 14:14
This hack is not equivalent to H5P's inherent embed feature. I am just instructing Moodle's theme to use the "embed" layout which display the main content of any page without the header+footer+block-areas.
While H5P's inherent embed is more sophisticated, and includes that h5p-resize.js code which is handling the resize of the iframe, no matter where you embed it.

Looking at the h5p-resize.js ... If you somehow add a redundant "&h5p=1" at the end of your iframe src (url) you might get it to work on your iframe.

**Comment by nickvarney** [comment] 2017-01-11 14:26
@nadavkav Perhaps I need to retry your plugin as my embed _did_ bring in the header, footer and all block areas from the left hand side when I tried it?? I am using a clone of the Moodle core theme 'More' (in Moodle 3.1) which is pretty basic. Perhaps you could try it with More and see if you get the desired results?

**Comment by nadavkav** [comment] 2017-01-11 14:46
@nickvarney , just make sure you add the part that changes the page layout in Moodle.
the "emebed" layout in all Moodle themes suppose to be the same. only content.
So if it is not working in the More theme, then you probably missed some code.
like:
```
if ($isembeded) {
$PAGE->set_pagelayout('embedded');
}

```

**Comment by nadavkav** [comment] 2017-01-11 14:48
Here is a proper link from one of the systems in which I am using this hack:
https://github.com/nadavkav/moodle-davidson/blob/moodle_31_davidson/mod/hvp/view.php#L51-L53

**Comment by wullie** [comment] 2017-01-11 15:31
@nadavkav I tried that onto the end of the src, but no luck unfortunately.

I'll stick with embedding it from the h5p site just now until there is something officially released. I think that the issue is only likely with the accordion due to the resizing of the available space.

Thanks anyway

**Comment by nadavkav** [comment] 2017-01-11 16:24
I on vacation (at beautiful Amsterdam) when I am back next week or so, I will try to figure it out, as one of our teachers on one of the Moodle systems that uses H5P also mentioned it. and it also been too long since I tweaked anything in the H5P code. and it's time I stick my fingers back in the code ;-)

**Comment by wullie** [comment] 2017-01-11 16:40
Thanks @nadavkav

**Comment by vaughany** [comment] 2017-01-16 10:09
Hi all. The company I work for has just started using H5P in a big way, but one of the issues we're facing is much the same as mentioned in this thread: embedding. To be honest, the only resource the company really wants to embed is the 'timeline' resource at the top of each course, because it looks great (thanks, H5P devs!) but if a consequence of this is all things embeddable everywhere, then everyone wins.

Consequently my employer has deemed it important enough to us that we'll be working on this ourselves, but after we've looked into backup and restore.

**Comment by nadavkav** [comment] 2017-01-16 16:03
Short update... 
We have started working on adding the H5P's "auto resize js" to the above mentioned  "ATTO insert embedded hvp activity". It might be ready in a week or so, as we have very little time allocated for it. (not to say it will take a week of work, of course ;-)

**Comment by nickvarney** [comment] 2017-01-16 16:15
@nadavkav The inclusion of the $isembeded code in our mod/hvp/view.php had no effect on how embeds presented in both the 'clean' and 'more' themes? We still see most of site's structure in the embed frame. I'm wondering whether these themes have a particular 'embedded' layout or not?

**Comment by nadavkav** [comment] 2017-01-16 16:50
Clean & More are based on Bootstrapbase, which has an "embedded" layout: https://github.com/moodle/moodle/blob/master/theme/bootstrapbase/layout/embedded.php

Are you sure you have all the code from the patch in your mod/hvp/view.php ?
(is it similar to: https://github.com/nadavkav/moodle-davidson/blob/moodle_31_davidson/mod/hvp/view.php ?)

**Comment by nickvarney** [comment] 2017-01-17 15:14
Thanks @nadavkav . Yes I've even used a copy of that view.php file to double check I hadn't made an error with my first attempt. It still displays too much in Clean, More and our clone of More.

We are using the latest release candidate of h5p rc1.0-rc.5. Are you on the same build? Are you able to switch your theme to Clean and More to test? Thanks for your help.

**Comment by nadavkav** [comment] 2017-01-17 20:00
I have tested it on Clean & More themes and it looks "clean" just the H5P content.
btw, if you add some "Intro" text, it will show above the H5P activity, which I think is good, in case some instructions are needed. And again, if it is not used, then the H5P content is the only thing that is displayed.
Hope you are not referring to it.

**Comment by nickvarney** [comment] 2017-01-20 12:15
@nadavkav Hmm, most odd. I still got everything displayed in an embed when I try it on a brand new,  fresh new install of Moodle 3.1.4 run locally on my machine!? When I say everything I do mean the nav bar, breadcrumb, all the blocks on the LH side of the course page, not just text above the embed. 
What am I doing wrong? 

- h5p installed. 
- h5p libraries installed. 
- Your atto editor plugin installed and the atto toolbar config edited so the button displays. 
- The view.php file edited to include the embedded page layout code you have posted. 

Anything missing?

**Comment by nadavkav** [comment] 2017-01-21 16:27
Nope. nothing is missing.
Can you send me a link with some temporary login credentials that I can look at it.
You can send an email to "my github user" @ gmail

**Comment by Nab59** [comment] 2017-04-29 06:01
Hi,

This is my first post on github.
I read your posts and i need help for my case. I explain.
My moodle site is version 3.2.2. I am in the same situation as nickvarney.  When integrate H5P content, I see the nav bar, course title, breadcrumb, then the h5p content, then all the blocks on the LH side of the course page and then the footer.

Could someone help please ?

**Comment by nadavkav** [comment] 2017-04-29 11:39
Digging into this...
It seems I shared link to github repositories that are not up to date, and the tiny but important difference between them cause this issue. So, here is what you need to fix to get it running for you:
The HVP Atto button is passing the "isembedded=1" param to the hvp/view.php file:
https://github.com/nadavkav/moodle-atto_hvp/blob/master/yui/src/button/js/button.js#L172
But in the current link I shared (in the past) it looks like one of our programmers changed the param to "embed" :cry: :
https://github.com/nadavkav/moodle-davidson/blob/moodle_31_davidson/mod/hvp/view.php#L28
And this is why the IFRAME display the HVP activity using the "incourse" theme layout and not the "embedded" layout.

So, to fix this, just change:
https://github.com/nadavkav/moodle-davidson/blob/moodle_31_davidson/mod/hvp/view.php#L28
to: "$isembeded = optional_param('isembedded', false, PARAM_BOOL);"

**Comment by Nab59** [comment] 2017-04-29 13:49
Hi Nadav,

Yes, now it works.

thanks so much.

**Comment by nadavkav** [comment] 2017-04-29 14:19
Great new :smile:

**Comment by Nab59** [comment] 2017-04-29 14:25
Now I will be able to take full advantage of this plugin.

**Comment by nadavkav** [comment] 2017-04-29 14:32
Moodle 3.3 (which is out in a few days) will also have activity Stealth mode (see demo: http://prototype.moodle.net/stealth/) with which you can have an H5P activity on the course that is not visible on the front page of the course for the students, BUT you can use it (link to it) by using the H5P Atto plugin. and only then the students can use it. which is perfect for our case scenario.

**Comment by Nab59** [comment] 2017-04-29 17:55
Oh, great news.
thank you for the information. 

I will folow.

**Comment by giselebrugger** [comment] 2017-06-10 22:52
Thank you a lot @Nadavkav. I'm using Fordson Theme with moodle 3.3 and is perfect embed.

**Comment by dgcruzing** [comment] 2017-09-17 06:22
nadavkav, 
Sorry to be painful, spent most the day on this and getting the same as above on April 29th.. and have edited files correctly. 
running 3.1.1 (Build: 20160711)
Theme - Pioneer
H5P - 1.5 2017083100
anything else I can try?
Thanks in advance

**Comment by Nab59** [comment] 2017-09-17 19:40
Hi Nadav,
Hope you are doing well.

I wonder if we can have the same H5P integration in an other editor like TinyMCE ?

thanks in advance for your reply.

**Comment by nadavkav** [comment] 2017-09-18 06:27
Hi @Nab59 , 
I am not aware of any TinyMCE integration. I think it can take a few hours to make (base on the code from the Atto plugin) but since it is deprecated by Moodle core team... I am not sure if this will get developed.
All the Moodle systems I know moved to Moodle 3.3 with Atto. I advise to move forward to Atto as well.

**Comment by nadavkav** [comment] 2017-09-20 17:55
There is no special CSS class added when the H5P activity is embedded (with IFRAME), so there is no easy way to hide it. 
What I usually recommend is to remove the title and place a &nbsp char instead. it's a workaround. I know.

**Comment by patsej** [comment] 2017-09-20 21:01
Thx!
I could get rid of the title with small changes in view.php.
The last <style> tag helps to remove the unnecessary space before the h5p (video in my case)
Note that I haven't tested it on other cases.

> // Print page HTML.
> echo $OUTPUT->header();
> **`if (! $isembedded) {`**
> &nbsp;&nbsp;&nbsp;&nbsp;echo $OUTPUT->heading(format_string($content['title']));
> &nbsp;&nbsp;&nbsp;&nbsp;echo '&lt;div class="clearer"&gt;&lt;/div&gt;';
> **`}`**
> 
> // Print any messages.
> \mod_hvp\framework::printMessages('info', \mod_hvp\framework::messages('info'));
> \mod_hvp\framework::printMessages('error', \mod_hvp\framework::messages('error'));
> 
> // Print intro.
> if (trim(strip_tags($content['intro']))) {
>  &nbsp;&nbsp;&nbsp;&nbsp;   **`echo "<style>.mod_introbox {padding:0px} </style>" ;`**

The only remaining issue is the size of the iframe. It is too small vertically for the video and the controls.
The Javascript responsible for resizing the iframe, included by ATTO, does not do its job properly.
Any idea?

**Comment by thomasmars** [comment] 2017-10-18 13:54
@nadavkav Did you ever create a pull request for this ?

**Comment by nadavkav** [comment] 2017-10-18 21:31
@thomasmars , No. as it always seemed like a hack, and hoped I find time to finish the filter/hvp I started to develop long time ago, instead. (I am getting there, I can see it on the horizon...)

**Comment by Avemaar** [comment] 2018-01-27 12:35
First of all H5p is such a great tool,but it would be great if
it would be possible embedding into moodle without the <iframe>
as mentioned by others like in tinyMc editor or Embed the (the real, direct) content
because iframe has some additional(an unnecessarily ) content.
I would work on this but have no idea

**Comment by thomasmars** [comment] 2018-01-31 15:00
Hi. I suggest you start by making yourself familiar with how the embedding is working currently and try to figure out how it can be improved upon. Determine some clear improvements you would like to make and create a new issue for discussing how this can be implemented most efficiently and without any regression issues. Finally if the changes are unproblematic a Pull Request should be made.
To start out have a look at embed: https://github.com/h5p/h5p-moodle-plugin/blob/master/embed.php

**Comment by Aditchoudhary** [comment] 2018-08-31 03:54
I have h5p file. now i want to view that file in HTML.

Please help in best and easiest way

**Comment by thomasmars** [comment] 2018-09-03 12:34
@Aditchoudhary This is not related to this topic. In the future please post questions in the H5P.org forums.

If you have an H5P-enabled website you can upload the .h5p file there and embed your content within an HTML file, instructions for embedding are found in the H5P.org documentation. If you wish to not use a H5P-enabled site there are no official resources that supports just showing an .h5p file directly in HTML

**Comment by danielneis** [comment] 2019-02-01 19:59
Hello,

i succesfully embedded the H5P content with the iframe method using the embed.php  file instead of the view.php file without any modifications to h5p. Looking forward to have that atto button using this to avoid hacks on the plugin.

**Comment by thomasmars** [comment] 2019-08-19 12:47
In its current state it is possible to embed H5P content into other Moodle resources, so closing this issue.
For development of an ATTO plugin or filter for H5P please open a separate issue or pull request.

**Closed by thomasmars** 2019-08-19 12:47 UTC
Labels: enhancement
