### ISSUE TITLE
H5P Moodle-plugin doesn't have embed-button

### ISSUE THREAD

**Issue by Jarvil** [h5p/h5p-moodle-plugin#92] opened 2016-07-06 04:39 UTC
Hello,

At the moment there is no way to get the embed code from a H5P-content that is uploaded to the Moodle H5P-plugin.

I would like to see an feature where H5P- Moodle -plugin would have "embed" button as an option in the settings that could be turned on or off just like the "download" and "copyright" buttons are. 

This way I could embed H5P-content straight on the course "front page" for example in the topic 1 -section instead of using it allways in a activity module.

**Comment by icc** [comment] 2016-07-06 08:12
This looks like a duplicate of #30 – which is about adding a shortcode and button to the wysiwyg for inserting content into the other resources in a course.

It's important to remember that H5P is an activity in Moodle and must belong to a course. This means that the users must participate in that course to be able to view the H5P. Having the standard Embed button, like in WordPress or Drupal, might cause confusing as the author will be able to see it and embed it everywhere, but people not part of the course will get permission denied.

It might be that H5P should have been some sort of Universal Resource in Moodle, but the way Moodle is built and structured doesn't really allow for that.

Feel free to provide your thoughts or re-open if you disagree.

**Comment by daya-cd** [comment] 2016-07-28 16:05
Can the activity be called using web service ?

**Comment by tmkettunen** [comment] 2017-01-27 14:10
> It's important to remember that H5P is an activity in Moodle and must belong to a course. This means that the users must participate in that course to be able to view the H5P.

You can actually add activities to Moodle frontpage also. And also the teachers have the option to allow guest access to their courses. If the site does not force login and the course allows guests, the resources in the course are available to everyone even without a user account.

If it would be possible to have the standard Embed button, like in WordPress or Drupal, my opinion is that the teacher is responsible for allowing or denying the access to their materials. It should be enough to prompt them before copying the embed code that users need access to the original H5P activity in order to view the embedded material.

Here's one example of a totally open Moodle with access to all the published courses without a login:
http://www.becult.org/

**Comment by icc** [comment] 2017-01-30 07:28
Ah, I see how this could be useful. But we will have to create a solution so that it's easy for the embedder to know who can see this. Perhaps only the teacher/manager should be able to view the embed code. 

Sidenote; the embed code can stop(or be limited to a certain domain) working if the web server sets the X-Frame-Options header.

**Closed** 2019-08-19 13:31 UTC
