### ISSUE TITLE
Embed dissappears with Collpased topics course format

### ISSUE THREAD

**Issue by Jarvil** [h5p/h5p-moodle-plugin#190] opened 2018-01-03 09:16 UTC
Hello,

There is a problem with Collapsed topic and H5P Embed -feature (iframe). 

Tested with Moodle 3.3, Mod_hvp 1.6 and format_topcoll 3.3.1.0 (2017042202) and Clean-theme

Steps to repeat;

1. Embed H5P activity to some section f.ex section 1
2. Click "close all" to fold all sections
3. Edit some random activity on the course (no need to edit it) and select "save and return to course"
4. Expand the section 1 and notice how the embedded H5P-activity isn't displayed, it only displays the bottom bar of the embedded H5P-activity
5. If you refresh the page with F5 then the embedded activity is displayed.

So the problem is that embedded H5P-activity isn't displayed if you fold all sections -> edit something -> return to the cousre frontpage until you manually refresh the page.

![h5p1](https://user-images.githubusercontent.com/15193418/34514709-60bcd480-f077-11e7-8995-c2081a5175c4.PNG)

![h5p2](https://user-images.githubusercontent.com/15193418/34514716-69963ede-f077-11e7-9575-68202445260d.png)

![h5p3](https://user-images.githubusercontent.com/15193418/34514720-6c59f048-f077-11e7-9fe8-3f14a8b5da6d.png)

![h5p4](https://user-images.githubusercontent.com/15193418/34514722-6ef9dd68-f077-11e7-86af-c0f86ad54f29.png)

![h5p5](https://user-images.githubusercontent.com/15193418/34514724-71b49d4a-f077-11e7-8913-1c90759a3ad8.png)

![h5p6](https://user-images.githubusercontent.com/15193418/34514728-74bd21c4-f077-11e7-9709-05d5e7392b5e.PNG)

![h5p7](https://user-images.githubusercontent.com/15193418/34514730-78187c56-f077-11e7-98eb-7f88f8c0e5bd.PNG)

![h5p8](https://user-images.githubusercontent.com/15193418/34514734-7b8200d8-f077-11e7-8cf2-58c0dd25843c.PNG)

![h5p9](https://user-images.githubusercontent.com/15193418/34514736-7f199b0c-f077-11e7-9c56-eb8e3c7bd926.PNG)

![h5p10](https://user-images.githubusercontent.com/15193418/34514740-822aba74-f077-11e7-8372-d25d8d64684e.PNG)

![h5p11](https://user-images.githubusercontent.com/15193418/34514741-8577aab6-f077-11e7-936f-8c0d0e161da4.PNG)

**Comment by falcon-git** [comment] 2018-01-11 19:25
If H5P is rendered with 0 height a resize event needs to be triggered when it gets more height. If someone starts digging into how we can now that the container is being expanded let us know and we can provide the code needed to make H5P resize itself.

**Comment by Jarvil** [comment] 2018-01-16 06:06
Hello,

Developer of Grid is asking;

Yes I can replicate. But there is a problem. The H5P mod script is a dynamic one that orchestrates itself on page load to generate the markup required to the available space (there is a resize script to cope with window resize). But if the script detects that the content is hidden (i.e. display: none) then it does not render it. When the container 'display' is changed by CT then the script is unaware that it needs to recalculate things etc.

Looking at h5p-resizer.js with:

  // Let h5p iframes know we're ready!
  var iframes = document.getElementsByTagName('iframe');
  var ready = {
    context: 'h5p',
    action: 'ready'
  };
  for (var i = 0; i < iframes.length; i++) {
    if (iframes[i].src.indexOf('h5p') !== -1) {
      iframes[i].contentWindow.postMessage(ready, '*');
    }
  }
there might be a way of telling the H5P frames when the state changes and therefore to redraw.

**Comment by timothyylim** [comment] 2018-01-16 14:12
@falcon-git , isn't it possible to trigger resize on the H5P as soon as the container is expanded?

**Comment by monnardj** [comment] 2018-01-16 14:28
Possible solution : in /mod/hvp/embed.php, add a MutationObserver on the iframe parent element <div class="sectionbody toggledsection" ...> (this is the element whose _display_ attribute changes from none to block when the topic is expanded). When a change in _display_ is detected, call the h5p-resizer script.
See [JavaScript/jQuery: How to trigger an event when “display: none” is removed?](https://stackoverflow.com/questions/37168158/javascript-jquery-how-to-trigger-an-event-when-display-none-is-removed)

**Comment by falcon-git** [comment] 2018-01-16 18:30
@timothyylim I can't think of any clean way of doing that. The best is if the resize is triggered when the user expands it, instead of H5P listening for a resize via mutation observers or timers. There are plenty of articles online about why timers and mutation observers should be avoided.

**Comment by gjb2048** [comment] 2019-07-30 12:51
Is this still an issue?

**Comment by adpe** [comment] 2019-08-07 15:26
Hello @timothyylim and @gjb2048 

We're using our own course format but extended from `topcoll` and encounter something similar. Here (https://cdnapisec.kaltura.com/index.php/extwidget/preview/partner_id/1756241/uiconf_id/26625532/entry_id/1_0zntyya0/embed/dynamic) is the video which shows, that after closing fullscreen, the div gets a height and width of 0px.

Maybe the issue is the same? If not, I'll create a new one.

Greets,
Adrian

**Comment by thomasmars** [comment] 2019-08-20 13:13
If you're using a special script or container/accordion that intializes H5P content with less than full height you will have to notify the H5P that it should resize when it is expanded.
This can be done by triggering the 'resize' event on the browser window, e.g.:
`window.dispatchEvent(new Event('resize'))`

**Closed by thomasmars** 2019-08-20 13:13 UTC

**Comment by adpe** [comment] 2019-09-30 15:26
> window.dispatchEvent(new Event('resize'))

Doesn't work for us. I've now done an own hack to set the height to 1px, similar to yours in this https://github.com/h5p/h5p-php-library/blob/7bc8666f309220a0eb93bca49aaa741bb013b26a/js/h5p.js#L253-L290.

PS: It only occurs with the branching scenario and I saw that's still beta.
