### ISSUE TITLE
Failing Translation Code

### ISSUE THREAD

**Issue by ekuncoro** [h5p/h5p-moodle-plugin#195] opened 2018-01-29 23:59 UTC
The initial error is coming up around line 1624 of the file h5p.classes.php. The code is catching an exception and passing the exception's message to a function that that is trying translate the message to a Moodle lang string with a "user-friendly" message. Unfortunately, at this point they discard the exception making troubleshooting very difficult without modification of the code. The translation code is failing because the exception is not one that it has been written to recognise and the value it returns then causes Moodle's language system to (correctly) throw an exception. This error is only a symptom of the actual error.

The actual error is a general low-level failure to read a file triggered in the Moodle file system functions while trying to store files from a tempory folder generated by h5p to Moodle's internal file store. The code is trying to copy a file called library.json to the file store, but this file does not exist in the tempory area. This is occurring around line 566 in the function exportFileTree in classes/file_storage.php. This file seems to exist for newly created activity instances, but not for ones created with previous versions of the code (and is not referenced in previous versions of the code).

**Comment by thomasmars** [comment] 2018-01-31 15:21
Thank you for reporting this. I have created an issue for looking into the translation issue and resolving it at: https://github.com/h5p/h5p-moodle-plugin/issues/195.

For the actual error, have you recently upgraded from an old version of H5P ? Could you give some more context on what you were doing when this happens, and how we can reproduce it ? Library.json should've existed for all content since the original specification for .h5p files. Also do you have the exact PHP error that you're getting when this happens ?

Thanks again for reporting this.

**Comment by ekuncoro** [comment] 2018-02-05 04:37
Here's some details extracted from the logs.

The previous installed version is (extracted from the version.php file).
$plugin->version   = 2017083100;
$plugin->requires  = 2013051403;
$plugin->cron      = 0;
$plugin->component = 'mod_hvp';
$plugin->maturity  = MATURITY_STABLE;
$plugin->release   = '1.5';
The version being tested is
$plugin->version   = 2017112800;
$plugin->requires  = 2013051403;
$plugin->cron      = 0;
$plugin->component = 'mod_hvp';
$plugin->maturity  = MATURITY_STABLE;
$plugin->release   = '1.6';
The following log messages are generated by the installed version.
[23-Jan-2018 14:31:59 Australia/Melbourne] PHP Notice:  exportFileTree /deployments/chisholm/var/www/moodle_data
s/chisholmdata/temp/hvp-5a66acaf43c4a/H5P.ImageJuxtaposition-1.1/ library.json<
<ul style="text-align: left" data-rel="backtrace"><li>line 566 of /mod/hvp/classes/file_storage.php: call to deb
ugging()</li><li>line 153 of /mod/hvp/classes/file_storage.php: call to mod_hvp\file_storage::exportFileTree()</
li><li>line 1618 of /mod/hvp/library/h5p.classes.php: call to mod_hvp\file_storage->exportLibrary()</li><li>line
 1969 of /mod/hvp/library/h5p.classes.php: call to H5PExport->createExportFile()</li><li>line 94 of /mod/hvp/cla
sses/view_assets.php: call to H5PCore->filterParameters()</li><li>line 64 of /mod/hvp/classes/view_assets.php: c
all to mod_hvp\view_assets->getfilteredparameters()</li><li>line 44 of /mod/hvp/view.php: call to mod_hvp\view_a
ssets->__construct()</li></ul> in /deployments/chisholm/var/www/html/chisholm/lib/weblib.php on line 3111
[23-Jan-2018 14:31:59 Australia/Melbourne] PHP Notice:  Exception caught in H5P createExportFile
tmpPath /deployments/chisholm/var/www/moodle_datas/chisholmdata/temp/hvp-5a66acaf43c4a
exportFolder
Cannot read file. Either the file does not exist or there is a permission problem.
#0 /deployments/chisholm/var/www/html/chisholm/mod/hvp/classes/file_storage.php(567): stored_file->copy_content_
to('/deployments/ch...')
#1 /deployments/chisholm/var/www/html/chisholm/mod/hvp/classes/file_storage.php(153): mod_hvp\file_storage::exportFileTree('/deployments/ch...', 1, 'libraries', '/H5P.ImageJuxta...')
#2 /deployments/chisholm/var/www/html/chisholm/mod/hvp/library/h5p.classes.php(1618): mod_hvp\file_storage->exportLibrary(Array, '/deployments/ch...', NULL)
#3 /deployments/chisholm/var/www/html/chisholm/mod/hvp/library/h5p.classes.php(1969): H5PExport->createExportFile(Array)
#4 /deployments/chisholm/var/www/html/chisholm/mod/hvp/classes/view_assets.php(94): H5PCore->filterParameters(Array)
#5 /deployments/chisholm/var/www/html/chisholm/mod/hvp/classes/view_assets.php(64): in /deployments/chisholm/var/www/html/chisholm/lib/weblib.php on line 3111
[23-Jan-2018 14:31:59 Australia/Melbourne] Default exception handler: Coding error detected, it must be fixed by a programmer: Invalid string identifier. The identifier cannot be empty. Please fix your get_string() call. Debug: 32767
Error code: codingerror
* line 6903 of /lib/moodlelib.php: coding_exception thrown
* line 434 of /mod/hvp/classes/framework.php: call to get_string()
* line 1629 of /mod/hvp/library/h5p.classes.php: call to mod_hvp\framework->t()
* line 1969 of /mod/hvp/library/h5p.classes.php: call to H5PExport->createExportFile()
* line 94 of /mod/hvp/classes/view_assets.php: call to H5PCore->filterParameters()
* line 64 of /mod/hvp/classes/view_assets.php: call to mod_hvp\view_assets->getfilteredparameters()
* line 44 of /mod/hvp/view.php: call to mod_hvp\view_assets->__construct()

And here's a couple of code changes I made in order to get the log messages. In the createExportFile in h5p.classes.php
// Export required libraries
$this->h5pC->fs->exportLibrary($library, $tmpPath, $exportFolder);
}
catch (Exception $e) {
  //CLIENT-SPECIFIC CHANGE: RETAIN
  // Debug code.
debugging(
  "Exception caught in H5P createExportFile \ntmpPath $tmpPath\nexportFolder $exportFolder\n" .
  $e->getMessage() . "\n" . $e->getTraceAsString()
);
//END: CLIENT-SPECIFIC CHANGE
$this->h5pF->setErrorMessage($this->h5pF->t($e->getMessage()), 'failed-creating-export-file');
H5PCore::deleteFileTree($tmpPath);
return FALSE;
}

// Do not add editor dependencies to h5p json.
And in the file file_storage.php
private static function exportFileTree($target, $contextid, $filearea, $filepath, $itemid = 0) {
    // Make sure target folder exists.
    if (!file_exists($target)) {
        mkdir($target, 0777, true);
    }

    // Read source files.
    $fs = get_file_storage();
    $files = $fs->get_directory_files($contextid, 'mod_hvp', $filearea, $itemid, $filepath, true);

    foreach ($files as $file) {
        // Correct target path for file.
        $path = $target . str_replace($filepath, '/', $file->get_filepath());

        if ($file->is_directory()) {
            // Create directory.
            $path = rtrim($path, '/');
            if (!file_exists($path)) {
                mkdir($path, 0777, true);
            }
        } else {
            // Copy file.
            debugging("exportFileTree $path " . $file->get_filename() . "\n");
            $file->copy_content_to($path . $file->get_filename());
        }
    }
}

**Comment by thomasmars** [comment] 2018-02-05 08:18
Thanks, it looks like this most likely is a permission issue with your moodle data folder ( /deployments/chisholm/var/www/moodle_datas/chisholmdata ). Please make sure that your web server has the permissions to read, write and execute files recursively in the data folder. There are some additional Moodle resources for how you can do this at [Moodle data guide](https://docs.moodle.org/24/en/Security_recommendations#Running_Moodle_on_a_shared_hosting_environment), [ownership and permissions](https://docs.moodle.org/20/en/Creating_Moodle_site_data_directory#Ownership_and_permissions) and this [Moodle thread](https://moodle.org/mod/forum/discuss.php?d=199549).

**Comment by ekuncoro** [comment] 2018-02-05 23:04
A permissions problem was one of our dev's initial assumptions, but that does not appear to be the case. The temp area in the moodledata directory is owned by the apache user used for the web server and the plugin has been able to successfully create its temp directory. I've also confirmed the permissions are correct in the file store area. I've also replicated the same problem on my local dev environment by backing up and restoring the course at the point where it has a problem, but only with existing activities, not with freshly created ones. 

Would you like us to send you the course backup?

Here is a listing of the temp directory created by a failed attempt to access one of the plugins in that course.
[greg@curplelea temp]$ ls -laR hvp-5a78dd0eb471c/
hvp-5a78dd0eb471c/:
total 16
drwxrwxrwx 4 apache apache 4096 Feb  6 09:39 .
drwxrwxrwx 7 apache apache 4096 Feb  6 09:48 ..
drwxrwxrwx 3 apache apache 4096 Feb  6 09:39 content
drwxrwxrwx 5 apache apache 4096 Feb  6 09:39 H5P.ImageJuxtaposition-1.1

hvp-5a78dd0eb471c/content:
total 16
drwxrwxrwx 3 apache apache 4096 Feb  6 09:39 .
drwxrwxrwx 4 apache apache 4096 Feb  6 09:39 ..
-rw-rw-rw- 1 apache apache  455 Feb  6 09:39 content.json
drwxrwxrwx 2 apache apache 4096 Feb  6 09:39 images

hvp-5a78dd0eb471c/content/images:
total 296
drwxrwxrwx 2 apache apache   4096 Feb  6 09:39 .
drwxrwxrwx 3 apache apache   4096 Feb  6 09:39 ..
-rw-rw-rw- 1 apache apache 222316 Feb  6 09:39 imageAfter-5a2f5c5a405ee.png
-rw-rw-rw- 1 apache apache  67913 Feb  6 09:39 imageBefore-5a2f5c5773c5c.png

hvp-5a78dd0eb471c/H5P.ImageJuxtaposition-1.1:
total 20
drwxrwxrwx 5 apache apache 4096 Feb  6 09:39 .
drwxrwxrwx 4 apache apache 4096 Feb  6 09:39 ..
drwxrwxrwx 2 apache apache 4096 Feb  6 09:39 language
drwxrwxrwx 2 apache apache 4096 Feb  6 09:39 scripts
drwxrwxrwx 2 apache apache 4096 Feb  6 09:39 styles

hvp-5a78dd0eb471c/H5P.ImageJuxtaposition-1.1/language:
total 8
drwxrwxrwx 2 apache apache 4096 Feb  6 09:39 .
drwxrwxrwx 5 apache apache 4096 Feb  6 09:39 ..

hvp-5a78dd0eb471c/H5P.ImageJuxtaposition-1.1/scripts:
total 8
drwxrwxrwx 2 apache apache 4096 Feb  6 09:39 .
drwxrwxrwx 5 apache apache 4096 Feb  6 09:39 ..

hvp-5a78dd0eb471c/H5P.ImageJuxtaposition-1.1/styles:
total 8
drwxrwxrwx 2 apache apache 4096 Feb  6 09:39 .
drwxrwxrwx 5 apache apache 4096 Feb  6 09:39 ..
And here are the corresponding log messages from the same attempt.
[06-Feb-2018 09:47:40 Australia/Melbourne] PHP Notice:  exportFileTree /deployments/chisholm/var/www/moodle_datas/chisholmdata/temp/hvp-5a78df0c2ba50/H5P.ImageJuxtaposition-1.1/ library.json
•	line 566 of /mod/hvp/classes/file_storage.php: call to debugging()
•	line 153 of /mod/hvp/classes/file_storage.php: call to mod_hvp\file_storage::exportFileTree()
•	line 1618 of /mod/hvp/library/h5p.classes.php: call to mod_hvp\file_storage->exportLibrary()
•	line 1969 of /mod/hvp/library/h5p.classes.php: call to H5PExport->createExportFile()
•	line 94 of /mod/hvp/classes/view_assets.php: call to H5PCore->filterParameters()
•	line 64 of /mod/hvp/classes/view_assets.php: call to mod_hvp\view_assets->getfilteredparameters()
•	line 44 of /mod/hvp/view.php: call to mod_hvp\view_assets->__construct()
in /deployments/chisholm/var/www/html/chisholm/lib/weblib.php on line 3111 [06-Feb-2018 09:47:40 Australia/Melbourne] PHP Notice: Exception caught in H5P createExportFile tmpPath /deployments/chisholm/var/www/moodle_datas/chisholmdata/temp/hvp-5a78df0c2ba50 exportFolder Cannot read file. Either the file does not exist or there is a permission problem. #0 /deployments/chisholm/var/www/html/chisholm/mod/hvp/classes/file_storage.php(567): stored_file->copy_content_to('/deployments/ch...') #1 /deployments/chisholm/var/www/html/chisholm/mod/hvp/classes/file_storage.php(153): mod_hvp\file_storage::exportFileTree('/deployments/ch...', 1, 'libraries', '/H5P.ImageJuxta...') #2 /deployments/chisholm/var/www/html/chisholm/mod/hvp/library/h5p.classes.php(1618): mod_hvp\file_storage->exportLibrary(Array, '/deployments/ch...', NULL) #3 /deployments/chisholm/var/www/html/chisholm/mod/hvp/library/h5p.classes.php(1969): H5PExport->createExportFile(Array) #4 /deployments/chisholm/var/www/html/chisholm/mod/hvp/classes/view_assets.php(94): H5PCore->filterParameters(Array) #5 /deployments/chisholm/var/www/html/chisholm/mod/hvp/classes/view_assets.php(64): in /deployments/chisholm/var/www/html/chisholm/lib/weblib.php on line 3111 [06-Feb-2018 09:47:40 Australia/Melbourne] PHP Notice: Undefined index: Cannot read file. Either the file does not exist or there is a permission problem. in /deployments/chisholm/var/www/html/chisholm/mod/hvp/classes/framework.php on line 434 [06-Feb-2018 09:47:40 Australia/Melbourne] Default exception handler: Coding error detected, it must be fixed by a programmer: Invalid string identifier. The identifier cannot be empty. Please fix your get_string() call. Debug: 32767 Error code: codingerror * line 6903 of /lib/moodlelib.php: coding_exception thrown * line 434 of /mod/hvp/classes/framework.php: call to get_string() * line 1629 of /mod/hvp/library/h5p.classes.php: call to mod_hvp\framework->t() * line 1969 of /mod/hvp/library/h5p.classes.php: call to H5PExport->createExportFile() * line 94 of /mod/hvp/classes/view_assets.php: call to H5PCore->filterParameters() * line 64 of /mod/hvp/classes/view_assets.php: call to mod_hvp\view_assets->getfilteredparameters() * line 44 of /mod/hvp/view.php: call to mod_hvp\view_assets->__construct()

**Comment by thomasmars** [comment] 2018-02-06 07:55
Okay, thanks for the extra info. So when the exportFileTree function runs, does the original files exist, and it is not able to copy the folders ? Or is the original files gone as well ? 
It's not clear what's causing this, but if this is reproducible across systems it would definitely help for debugging to have the course backup that you use for import and a few steps to consistently reproduce it. You can send it to my github mail or thomas.marstrander (at) joubel (dot) com, and I'll try to reproduce and debug on my end.

**Comment by thomasmars** [comment] 2018-02-16 09:47
Hi,
The first error I get when attempting to restore the backup is that there are many files missing from it, in particular most of the library/content type files.
I'm not sure how this has happened, there could be several reasons for this, to name a few:
- Have you set $CFG->mod_hvp_backup_libraries to 0 ? This is a performance optimization which defaults to 1, but you can override it in your server's config.php. If it is off your libraries will not be backed up with your content, so this could be a reason that the libraries are not present.
- The server was not able to retrieve them when making the backup, i.e. they did not exist on the system at the time of backup, or the server did not have permission to retrieve them.
- The backup has somehow been corrupted

Can you test backing up a different(working) course, does the same thing happen with all courses that you backup ? and please check your config.php if the mod_hvp_backup_libraries option is set.
As a workaround for making the backed up file work you can make sure that you have all libraries you need for the backup installed before you restore the course. This way all the content will work when you restore the course.
It is important that the libraries are installed beforehand, because otherwise the site will think that they were installed during backup, even though they weren't and then start looking for them, but not find the files, because they were never there.

Hope this will help you make the backup work. Let me know how you get along.

**Comment by benIT** [comment] 2018-10-10 14:12
I encountered the following message after redeploying my moodle instance to a new environment:
```
Invalid string identifier. The identifier cannot be empty. Please fix your get_string() call.
Debug info: 32767
Error code: codingerror
Stack trace:

    line 6685 of /lib/moodlelib.php: coding_exception thrown
    line 370 of /mod/hvp/classes/framework.php: call to get_string()
    line 2897 of /mod/hvp/library/h5p.classes.php: call to mod_hvp\framework->t()
    line 136 of /mod/hvp/settings.php: call to H5PCore->checkSetupErrorMessage()
    line 89 of /lib/classes/plugininfo/mod.php: call to include()
    line 45 of /admin/settings/plugins.php: call to core\plugininfo\mod->load_settings()
    line 6933 of /lib/adminlib.php: call to require()
    line 19 of /admin/settings.php: call to admin_get_root()
```

After a quick debug session in `mod/hvp/classes/framework.php:370`:
```
        die($message);
        return get_string($translations_map[$message], 'hvp', $replacements);
```

This explicit message appears: `The mbstring PHP extension is not loaded. H5P needs this to function properly`. I fixed it as follow:

```
sudo apt install php5.6-mbstring
sudo phpenmod mbstring
sudo service apache2 restart
```

I hope this can help.
greetings,
ben

**Comment by thomasmars** [comment] 2018-10-10 14:16
Happy you got it to work :)

**Closed by thomasmars** 2018-10-10 14:16 UTC
