### ISSUE TITLE
Activities created in Moodle flickering on iPad

### ISSUE THREAD

**Issue by sarahjcotton** [h5p/h5p-moodle-plugin#237] opened 2018-12-12 16:34 UTC
When an activity that has been built in Moodle is displayed on an iPad it flickers on screen rendering it unusable. This is apparent in both Safari and Chrome. I've managed to get a video of this happening although it's not very good quality I'm afraid. This is using clean theme in 3.5.1 with version 2018113000  of H5P. Activities built on the H5P site and then embedded do not have the same issue.
https://solent.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=75df7efa-08b2-4784-921f-a9b4010f1cab

**Comment by thomasmars** [comment] 2018-12-13 08:31
Thanks for reporting this.
Can you give us some more info please ? 

1. Was this happening before version 2018113000 ?
2. How is this content being displayed ? Is it embedded on a course page from an activity within the same course ?
3. What iPad device, OS version and browser versions is this happening in ?
4. How exactly can we reproduce this ? Is this happening every time you view the H5P, or only under certain circumstances ?
5. Which H5P content type is being used, and which version of the H5P content type ? Does this happen when using other H5P content types ?
6. Are there any browser console errors ?

**Comment by thomasmars** [comment] 2018-12-14 09:41
Thank you for the details. I have created an issue for this in our public issue tracker, and will try to push it through as soon as possible: https://h5ptechnology.atlassian.net/browse/HFP-2469.

**Comment by Jarvil** [comment] 2019-01-04 12:48
Hello,

I'm experiencing flickering also with ios 12.1.1/Safari any progress on this?

**Comment by Jarvil** [comment] 2019-01-14 07:11
any progerss @thomasmars

**Comment by evsadmin** [comment] 2019-01-20 05:57
Hello,

I am experiencing the same problem.  I am using gnomio.com.  I am not sure of which version of moodle they use.

**Comment by troywilliams** [comment] 2019-01-22 00:13
Hi,

We are having the same problem with Safari and Firefox on iOS.

Thanks

**Comment by digitalskill** [comment] 2019-01-22 21:19
Hi guys - This script resolves when added into additional HTML. It's not ideal - but does the trick for us right now.

It seems to point that the current embedded script for H5P may need to set a min-height when doing measurements of internal content - (Jquery when meausreing elements 

<script>
// This is to remove the mobile flicker for mobile devices
window.addEventListener("load", function () {
window.setInterval(function(){ 
                       var iframes =  jQuery('body.mobiletheme:not(.h5p-no-frame) iframe[src*="hvp"]');
                       jQuery(iframes).each(function(i,obj){
                            jQuery(obj).contents().find('body').css('overflow','hidden');
                            var frameHeight = jQuery(obj).contents().find('iframe.h5p-iframe').css('height');
                           jQuery(obj).css('height',frameHeight);  
                           jQuery(obj).css('min-height',frameHeight);   
                      });
            }, 5);  
});
</script>

**Comment by sarahjcotton** [comment] 2019-01-23 09:08
> Hi guys - This script resolves when added into additional HTML. It's not ideal - but does the trick for us right now.
> 
> It seems to point that the current embedded script for H5P may need to set a min-height when doing measurements of internal content
> 
> <script> // This is to remove the mobile flicker for mobile devices window.addEventListener("load", function () { window.setInterval(function(){ var iframes = jQuery('body.mobiletheme:not(.h5p-no-frame) iframe[src*="hvp"]'); jQuery(iframes).each(function(i,obj){ jQuery(obj).contents().find('body').css('overflow','hidden'); var frameHeight = jQuery(obj).contents().find('iframe.h5p-iframe').css('height'); jQuery(obj).css('height',frameHeight); jQuery(obj).css('min-height',frameHeight); }); }, 5); }); </script>

This is great, thank you... we only have this version on our dev server at the moment but this fix might enable me to push it onto production if I add it to the plugin. We needed to upgrade to fix other issues but this one is worse than the ones we already have, so we've had to stop pushing the use H5P for the time being unfortunately .

**Comment by snafuy** [comment] 2019-01-23 18:40
See also https://h5p.org/node/400718 and https://h5ptechnology.atlassian.net/browse/HFP-2584

**Comment by kaitkrull** [comment] 2019-02-05 22:12
Hi! Just wanted to point to this https://h5p.org/comment/25177#comment-25177. Maybe it could help. What do you think about addressing iOS only and changing the H5P's library/js/h5p-resizer.js script to do not nothing when iOS is detected (so just to return)? Maybe there is still a better implementation to this.
I have not tested this directly in Moodle H5P plugin but can confirm that after doing a change in Wordpress H5P module and embedding from there to Moodle the flickering on iOS stopped. I think if this is an appropriate fix then this should be implemented to the core H5P resize script also. 
I also tried embedding H5P in Moodle without the resize script and it worked for iOS but messed up on other devices like Android and desktop which cannot handle the iframe size. So this has to be something to do with iOS handling iframe itself (can somebody confirm or explain what is so different on iOS?)

**Comment by Jarvil** [comment] 2019-02-07 07:30
@thomasmars  @icc @fnoks  any progress on fixing this? This makes Moodle with embedded H5P-activities virtually unusable.

**Comment by sarahjcotton** [comment] 2019-03-06 12:10
> @thomasmars @icc @fnoks any progress on fixing this? This makes Moodle with embedded H5P-activities virtually unusable.

I would also like to know if any progress has been made. Colleagues are regularly asking when the fix will be available as they would like to recommence using the module.

**Comment by thomasmars** [comment] 2019-03-07 14:52
This was fixed in https://github.com/h5p/h5p-php-library/commit/1a09b1a30e61fc9f6454f1e79a0f8f35290413fd.
It will be part of the upcoming release.

**Comment by sarahjcotton** [comment] 2019-03-19 09:18
We have been testing the patch ahead of the release and there are now large areas of white space appearing below some of the activity types. The Arithmetic Quiz and Guess the Answer types are ok, but the Image Juxtaposition, Document Tool and Hot Spot all have white space which pushes the rest of the content down the page. This is using Safari on an iPad. I've attached an image showing an example.
![h5p](https://user-images.githubusercontent.com/2684004/54594122-e9e83500-4a27-11e9-921f-81230c869e07.png)

**Comment by thomasmars** [comment] 2019-03-19 09:34
Thanks for reporting this, I've created an issue for handling it at https://h5ptechnology.atlassian.net/browse/HFP-2690 where you can follow along the progress.

**Comment by MartinSandberg** [comment] 2019-03-21 16:08
I will leace a comment here as well....

added the info here  (https://github.com/h5p/h5p-php-library/commit/1a09b1a30e61fc9f6454f1e79a0f8f35290413fd) previously but mayby more people will see it here;

The flickering problem is caused by Safari on iPhone / iPad / Mac handling responsive content in a responsive iframe different from eveyone else. At Xtractor we solved the flickering issue by making some small tweaks to the library/styles/hvp.css file.

library/styles/h5p.css ~row 17 in html.h5p-iframe, html.h5p-iframe > body {
/* xtractor change to stop iphones from flickering /
width: 1px;
min-width: 100%;
/width: 100%;
height: 100%;/
/ end xtractor */

library/styles/h5p.css ~row 27 after html.h5p-iframe, html.h5p-iframe > body {
/* XTRACTOR addition as the change above stopped fullscreen from working*/
html.h5p-fullscreen, html.h5p-iframe, html.h5p-iframe > body {
width: 100%;
height: 100%;
margin: 0;
padding: 0;
}
/* end XTRACTOR */

**Comment by thomasmars** [comment] 2019-08-20 14:39
This should be fixed, please re-open if you're continuing to observe the issue.

**Closed by thomasmars** 2019-08-20 14:39 UTC
